export const attributesConfig: {[key: string]: string} = {
  'Address': 'address',
  'T::Address': 'address',
  'AuthorityId': 'address',
  '<Lookup as StaticLookup>::Source': 'address',
  'AccountId': 'address',
  'T::AccountId': 'address',
  'LookupSource': 'address',
  'T::LookupSource': 'address',
  'PropIndex': 'proposal',
  'ReferendumIndex': 'referendum',
  'Compact<ReferendumIndex>': 'referendum',
  'SessionIndex': 'session',
  'BlockNumber': 'block',
  'AccountIndex': 'account',
  'EthereumAddress': 'ethereumAddress',
  'Balance': 'balance',
  'T::Balance': 'balance',
  'BalanceOf': 'balance',
  'BalanceOf<T>': 'balance',
  'T::BalanceOf': 'balance',
  'Compact<Balance>': 'balance',
  'Compact<BalanceOf>': 'balance',
  'Moment': 'date',
  'Compact<Moment>': 'date',
  'Bytes': 'bytes',
  'DownloadableBytesHash': 'downloadable',
  'bool': 'boolean'
};
